# Interactive session with Spark to explore Bronze results

This notebook uses the project virtual environment and repo-local paths only.

In [ ]:
from pathlib import Path
import os
import sys
import pandas as pd

repo_root = Path.cwd().resolve()
if not (repo_root / "bronze").exists():
    repo_root = Path("/home/dcamacho/dev/ProjectData").resolve()

source_sample_dir = repo_root / "sample_data"
source_dir = repo_root / "data/exports/projectA"
table_path = repo_root / "_tmp" / "bronze_pid_documents"

# Remove stale Spark/Python overrides from previous runs
for key in ["PYTHONPATH", "SPARK_HOME", "PYSPARK_PYTHON", "PYSPARK_DRIVER_PYTHON"]:
    os.environ.pop(key, None)
    
sys.path = [p for p in sys.path if "/opt/spark" not in p]

print("repo_root =", repo_root)
print("source_sample_dir =", source_sample_dir)
print("source_dir =", source_dir)
print("table_path =", table_path)
print("python_executable =", sys.executable)

print("Python:", sys.executable)
print("PYTHONPATH:", os.environ.get("PYTHONPATH"))

repo_root = /home/dcamacho/dev/ProjectData
source_sample_dir = /home/dcamacho/dev/ProjectData/sample_data
source_dir = /home/dcamacho/dev/ProjectData/data/exports/projectA
table_path = /home/dcamacho/dev/ProjectData/tmp/bronze_pid_documents
python_executable = /home/dcamacho/dev/ProjectData/.venv/bin/python
Python: /home/dcamacho/dev/ProjectData/.venv/bin/python
PYTHONPATH: None

In [2]:
import pyspark
print(pyspark.__file__)
print(pyspark.__version__)

/home/dcamacho/dev/ProjectData/.venv/lib/python3.9/site-packages/pyspark/__init__.py
3.5.1

In [3]:
python_executable = globals().get("python_executable", globals().get("current_python", sys.executable))
source_sample_dir_str = str(source_sample_dir)
source_dir_str = str(source_dir)
table_path_str = str(table_path)

!{python_executable} -m bronze.cli ingest \
    --source-dir "{source_sample_dir_str}" \
    --table-path "{table_path_str}" \
    --project-code Sample

26/08/29 14:23:45 WARN Utils: Your hostname, DC01NNCOL resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
26/08/29 14:23:45 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
:: loading settings :: url = jar:file:/home/dcamacho/dev/ProjectData/.venv/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/dcamacho/.ivy2/cache
The jars for the packages stored in: /home/dcamacho/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-febd1df3-c97e-4191-9698-b6e45b5e4928;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.2.0 in central
	found io.delta#delta-storage;3.2.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
:: resolution report :: resolve 180ms :: artifacts dl 8ms
	:: modules in use:
	io.delta#delta-spark_2.12;3.2.0 from central in [default]
	io.delta#delta-storage;3.2.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-febd1df3-c97e-4191-9698-b6e45b5e4928
	confs: [default]
	0 artifacts copied, 3 already retrieved (0kB/5ms)
26/08/29 14:23:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/08/29 14:23:52 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
{
  "ingest_run_id": "38ca3858-4266-4828-a33e-d92d256fa2ae",
  "files_in_batch": 4,
  "rows_inserted": 4,
  "rows_skipped_already_present": 0
}

In [4]:
# Keep the runtime clean for Spark. Do not set PYTHONPATH or SPARK_HOME manually here.
for key in ["PYTHONPATH", "SPARK_HOME", "PYSPARK_PYTHON", "PYSPARK_DRIVER_PYTHON"]:
    os.environ.pop(key, None)

print("Using Python:", sys.executable)
print("Python version:", sys.version)

Using Python: /home/dcamacho/dev/ProjectData/.venv/bin/python
Python version: 3.9.23 (main, Jun  4 2025, 08:55:38)
[GCC 9.4.0]

In [5]:
os.environ["SPARK_LOCAL_IP"] = "127.0.0.1"

In [6]:
from pyspark.sql import SparkSession
from delta import configure_spark_with_delta_pip


pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 150)

builder = (
    SparkSession.builder
    .master("local[*]")
    .appName("Interactive_Bronze_Exploration")
    .config("spark.driver.host", "127.0.0.1")
    .config("spark.driver.bindAddress", "127.0.0.1")
    .config("spark.driver.memory", "4g")
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
)

spark = configure_spark_with_delta_pip(builder).getOrCreate()
print("Spark ready:", spark.version)

your 131072x1 screen size is bogus. expect trouble

:: loading settings :: url = jar:file:/home/dcamacho/dev/ProjectData/.venv/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/dcamacho/.ivy2/cache
The jars for the packages stored in: /home/dcamacho/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-0d4099bd-5691-4c75-ba9a-5ca7bf02926b;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.2.0 in central
	found io.delta#delta-storage;3.2.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
:: resolution report :: resolve 193ms :: artifacts dl 8ms
	:: modules in use:
	io.delta#delta-spark_2.12;3.2.0 from central in [default]
	io.delta#delta-storage;3.2.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-0d4099bd-5691-4c75-ba9a-5ca7bf02926b
	confs: [default]
	0 artifacts copied, 3 already retrieved (0kB/4ms)
26/08/29 14:24:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

Spark ready: 3.5.1

In [7]:
# Load the table created by the CLI ingest run
path = str(table_path)
df = spark.read.format("delta").load(path)
print("Rows:", df.count())
df.show(5, truncate=False)

26/08/29 14:24:18 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

Rows: 4
+------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------+---------------------------------------------------------------------------+---------------------------+--------------------+--------------------------+------------------------------------+------------------+-------------+-----------------------+----------------------+----------------------------+----------------+---------------------+---------------+------------+-----------+
|bronze_id                           |content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |content_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |content_hash                                                    |file_size_bytes|source_path                                                                |source_filename            |source_last_modified|ingested_at               |ingest_run_id                       |originating_system|source_format|format_detection_method|client_document_number|document_number             |drawing_revision|drawing_revision_date|header_parse_ok|project_code|ingest_date|
+------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------+---------------------------------------------------------------------------+---------------------------+--------------------+--------------------------+------------------------------------+------------------+-------------+-----------------------+----------------------+----------------------------+----------------+---------------------+---------------+------------+-----------+
|03b3f29f-364f-4aed-8e2d-16880c0f579d|[3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 22 31 2E 30 22 20 65 6E 63 6F 64 69 6E 67 3D 22 55 54 46 2D 38 22 3F 3E 0A 3C 21 2D 2D 20 53 79 6E 74 68 65 74 69 63 20 44 45 58 50 49 2F 50 72 6F 74 65 75 73 20 50 26 49 44 20 65 78 70 6F 72 74 20 28 70 72 6F 6A 65 63 74 20 41 29 2E 20 53 74 72 75 63 74 75 72 65 20 69 73 20 69 6C 6C 75 73 74 72 61 74 69 76 65 3B 0A 20 20 20 20 20 63 6F 6E 66 69 72 6D 20 72 65 61 6C 20 65 6C 65 6D 65 6E 74 2F 61 74 74 72 69 62 75 74 65 20 6E 61 6D 65 73 20 61 67 61 69 6E 73 74 20 61 63 74 75 61 6C 20 65 78 70 6F 72 74 73 20 28 73 70 65 63 20 C2 A7 39 29 2E 20 2D 2D 3E 0A 3C 50 6C 61 6E 74 4D 6F 64 65 6C 3E 0A 20 20 3C 50 6C 61 6E 74 49 6E 66 6F 72 6D 61 74 69 6F 6E 20 4F 72 69 67 69 6E 61 74 69 6E 67 53 79 73 74 65 6D 3D 22 53 6D 61 72 74 50 6C 61 6E 74 20 50 26 61 6D 70 3B 49 44 22 20 53 63 68 65 6D 61 56 65 72 73 69 6F 6E 3D 22 33 2E 36 2E 31 22 20 44 61 74 65 3D 22 32 30 32 36 2D 30 35 2D 31 30 22 2F 3E 0A 20 20 3C 44 72 61 77 69 6E 67 20 4E 61 6D 65 3D 22 33 36 32 2D 30 39 2D 50 52 2D 50 49 44 2D 30 31 30 31 30 22 0A 20 20 20 20 20 20 20 20 20 20 20 4E 75 6D 62 65 72 3D 22 32 31 35 37 37 37 43 2D 33 36 32 30 39 2D 50 49 44 2D 30 30 32 31 2D 30 31 30 31 30 22 0A 20 20 20 20 20 20 20 20 20 20 20 52 65 76 69 73 69 6F 6E 3D 22 30 31 22 0A 20 20 20 20 20 20 20 20 20 20 20 52 65 76 69 73 69 6F 6E 44 61 74 65 3D 22 32 30 32 36 2D 30 35 2D 30 38 22 3E 0A 20 20 20 20 3C 47 65 6E 65 72 69 63 41 74 74 72 69 62 75 74 65 73 20 4E 75 6D 62 65 72 3D 22 31 22 3E 0A 20 20 20 20 20 20 3C 47 65 6E 65 72 69 63 41 74 74 72 69 62 75 74 65 20 4E 61 6D 65 3D 22 44 65 73 63 72 69 70 74 69 6F 6E 22 20 56 61 6C 75 65 3D 22 41 43 49 44 20 47 41 53 20 57 41 53 48 49 4E 47 20 43 4F 4C 55 4D 4E 22 2F 3E 0A 20 20 20 20 3C 2F 47 65 6E 65 72 69 63 41 74 74 72 69 62 75 74 65 73 3E 0A 20 20 3C 2F 44 72 61 77 69 6E 67 3E 0A 20 20 3C 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 79 73 74 65 6D 20 49 44 3D 22 53 59 2D 31 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 79 73 74 65 6D 22 3E 0A 20 20 20 20 3C 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 20 49 44 3D 22 53 47 2D 31 22 3E 0A 20 20 20 20 20 20 3C 50 69 70 69 6E 67 43 6F 6D 70 6F 6E 65 6E 74 20 49 44 3D 22 50 43 2D 31 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 47 61 74 65 56 61 6C 76 65 22 2F 3E 0A 20 20 20 20 20 20 3C 50 69 70 69 6E 67 43 6F 6D 70 6F 6E 65 6E 74 20 49 44 3D 22 50 43 2D 32 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 46 6C 61 6E 67 65 22 2F 3E 0A 20 20 20 20 3C 2F 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 3E 0A 20 20 20 20 3C 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 20 49 44 3D 22 53 47 2D 32 22 3E 0A 20 20 20 20 20 20 3C 50 69 70 69 6E 67 43 6F 6D 70 6F 6E 65 6E 74 20 49 44 3D 22 50 43 2D 33 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 43 68 65 63 6B 56 61 6C 76 65 22 2F 3E 0A 20 20 20 20 3C 2F 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 3E 0A 20 20 3C 2F 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 79 73 74 65 6D 3E 0A 3C 2F 50 6C 61 6E 74 4D 6F 64 65 6C 3E 0A]|<?xml version="1.0" encoding="UTF-8"?>\n<!-- Synthetic DEXPI/Proteus P&ID export (project A). Structure is illustrative;\n     confirm real element/attribute names against actual exports (spec §9). -->\n<PlantModel>\n  <PlantInformation OriginatingSystem="SmartPlant P&amp;ID" SchemaVersion="3.6.1" Date="2026-05-10"/>\n  <Drawing Name="362-09-PR-PID-01010"\n           Number="215777C-36209-PID-0021-01010"\n           Revision="01"\n           RevisionDate="2026-05-08">\n    <GenericAttributes Number="1">\n      <GenericAttribute Name="Description" Value="ACID GAS WASHING COLUMN"/>\n    </GenericAttributes>\n  </Drawing>\n  <PipingNetworkSystem ID="SY-1" ComponentClass="PipingNetworkSystem">\n    <PipingNetworkSegment ID="SG-1">\n      <PipingComponent ID="PC-1" ComponentClass="GateValve"/>\n      <PipingComponent ID="PC-2" ComponentClass="Flange"/>\n    </PipingNetworkSegment>\n    <PipingNetworkSegment ID="SG-2">\n      <PipingComponent ID="PC-3" ComponentClass="CheckValve"/>\n    </PipingNetworkSegment>\n  </PipingNetworkSystem>\n</PlantModel>\n|e44fe29961e23aa279cd9fffc5906bfd9a5b25ff2a30d6e3a6a74a33f56ad864|1040           |file:/home/dcamacho/dev/ProjectData/sample_data/projectA_dexpi_01010.xml   |projectA_dexpi_01010.xml   |2026-08-28 03:15:32 |2026-08-29 14:23:51.431827|38ca3858-4266-4828-a33e-d92d256fa2ae|SmartPlant P&ID   |DEXPI        |ORIGINATING_SYSTEM     |362-09-PR-PID-01010   |215777C-36209-PID-0021-01010|01              |2026-05-08           |true           |Sample      |2026-08-29 |

In [8]:
# Show a compact preview
visible_columns = [
    "document_number",
    "drawing_revision",
    "project_code",
    "source_filename",
    "file_size_bytes",
    "ingested_at",
    "content_text",
]

preview = df.select(*[c for c in visible_columns if c in df.columns]).limit(10).toPandas()
preview

,document_number,drawing_revision,project_code,source_filename,file_size_bytes,ingested_at,content_text
0,215777C-36209-PID-0021-01010,01,Sample,projectA_dexpi_01010.xml,1040,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- Synthetic DEXPI/Proteus P&ID export (project A). Structure is illustrative;\n confirm real elemen..."
1,A14-0001-001,A,Sample,projectB_postproc_0001.xml,870,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- Synthetic INGR ISO-15926 PostProc export (project B), OriginatingSystem=SPPID.\n PipingNetworkSeg..."
2,A22-0007-003,B,Sample,ambiguous_no_originator.xml,495,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- No OriginatingSystem present -> exercises the SEGMENT_TAGNAME fallback.\n A PipingNetworkSegment ..."
3,None,None,Sample,malformed_truncated.xml,429,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- Malformed export: the title block is broken before the revision can be read.\n Bronze must still ..."

## Delta history

In [9]:
from delta.tables import DeltaTable

try:
    delta_table = DeltaTable.forPath(spark, str(table_path))
    history_df = delta_table.history()
    history_df.select("version", "timestamp", "operation", "operationParameters").show(truncate=False)
except Exception as e:
    print(f"Unable to read Delta history: {e}")

+-------+-----------------------+---------+-------------------------------------------------------+
|version|timestamp              |operation|operationParameters                                    |
+-------+-----------------------+---------+-------------------------------------------------------+
|0      |2026-08-29 14:24:03.653|WRITE    |{mode -> ErrorIfExists, partitionBy -> ["ingest_date"]}|
+-------+-----------------------+---------+-------------------------------------------------------+

In [10]:
python_executable = globals().get("python_executable", globals().get("current_python", sys.executable))
source_sample_dir_str = str(source_sample_dir)
source_dir_str = str(source_dir)
table_path_str = str(table_path)

!{python_executable} -m bronze.cli ingest \
    --source-dir "{source_dir_str}" \
    --table-path "{table_path_str}" \
    --project-code A

:: loading settings :: url = jar:file:/home/dcamacho/dev/ProjectData/.venv/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/dcamacho/.ivy2/cache
The jars for the packages stored in: /home/dcamacho/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-8c30719c-7fc4-48a3-965e-169f82db03fd;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.2.0 in central
	found io.delta#delta-storage;3.2.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
:: resolution report :: resolve 193ms :: artifacts dl 10ms
	:: modules in use:
	io.delta#delta-spark_2.12;3.2.0 from central in [default]
	io.delta#delta-storage;3.2.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-8c30719c-7fc4-48a3-965e-169f82db03fd
	confs: [default]
	0 artifacts copied, 3 already retrieved (0kB/9ms)
26/08/29 14:24:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/08/29 14:24:29 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/08/29 14:24:33 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
{
  "ingest_run_id": "b0cde3ad-7e73-480e-992f-b31bc4102022",
  "files_in_batch": 4,
  "rows_inserted": 4,
  "rows_skipped_already_present": 0
}

In [11]:
preview = df.select(*[c for c in visible_columns if c in df.columns]).limit(10).toPandas()
preview

,document_number,drawing_revision,project_code,source_filename,file_size_bytes,ingested_at,content_text
0,362-09-PR-PID-01470,01,A,362-09-01470_Dexpi.xml,12537819,2026-08-29 14:24:45.642813,"<?xml version=""1.0"" encoding=""utf-8""?>\r\n<PlantModel xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">\r\n <!--Created with INGR ISO15926 P..."
1,362-92-PR-PID-02265,01,A,362-92-02265_Dexpi.xml,6669430,2026-08-29 14:24:45.642813,"<?xml version=""1.0"" encoding=""utf-8""?>\r\n<PlantModel xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">\r\n <!--Created with INGR ISO15926 P..."
2,362-09-PR-PID-01050,01,A,362-09-01050_Dexpi.xml,11926337,2026-08-29 14:24:45.642813,"<?xml version=""1.0"" encoding=""utf-8""?>\r\n<PlantModel xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">\r\n <!--Created with INGR ISO15926 P..."
3,362-09-PR-PID-01010,01,A,362-09-01010_Dexpi.xml,11819694,2026-08-29 14:24:45.642813,"<?xml version=""1.0"" encoding=""utf-8""?>\r\n<PlantModel xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">\r\n <!--Created with INGR ISO15926 P..."
4,215777C-36209-PID-0021-01010,01,Sample,projectA_dexpi_01010.xml,1040,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- Synthetic DEXPI/Proteus P&ID export (project A). Structure is illustrative;\n confirm real elemen..."
5,A14-0001-001,A,Sample,projectB_postproc_0001.xml,870,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- Synthetic INGR ISO-15926 PostProc export (project B), OriginatingSystem=SPPID.\n PipingNetworkSeg..."
6,A22-0007-003,B,Sample,ambiguous_no_originator.xml,495,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- No OriginatingSystem present -> exercises the SEGMENT_TAGNAME fallback.\n A PipingNetworkSegment ..."
7,None,None,Sample,malformed_truncated.xml,429,2026-08-29 14:23:51.431827,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<!-- Malformed export: the title block is broken before the revision can be read.\n Bronze must still ..."

In [12]:
try:
    delta_table = DeltaTable.forPath(spark, str(table_path))
    history_df = delta_table.history()
    history_df.select("version", "timestamp", "operation", "operationParameters").show(truncate=False)
except Exception as e:
    print(f"Unable to read Delta history: {e}")

+-------+-----------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|version|timestamp              |operation|operationParameters                                                                                                                                                     |
+-------+-----------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|1      |2026-08-29 14:24:50.893|MERGE    |{predicate -> ["(content_hash#1211 = content_hash#31)"], matchedPredicates -> [], notMatchedPredicates -> [{"actionType":"insert"}], notMatchedBySourcePredicates -> []}|
|0      |2026-08-29 14:24:03.653|WRITE    |{mode -> ErrorIfExists, partitionBy -> ["ingest_date"]}                                                                                                                 |
+-------+-----------------------+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [13]:
# Optional: time-travel example for version 0 if it exists
try:
    version_zero = spark.read.format("delta").option("versionAsOf", 0).load(str(table_path))
    print("Rows in version 0:", version_zero.count())
    version_zero.show(5, truncate=False)
except Exception as e:
    print(f"Version travel is unavailable yet: {e}")
finally:
    # keep the session alive until you explicitly stop it
    pass

Rows in version 0: 4
+------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------+---------------------------------------------------------------------------+---------------------------+--------------------+--------------------------+------------------------------------+------------------+-------------+-----------------------+----------------------+----------------------------+----------------+---------------------+---------------+------------+-----------+
|bronze_id                           |content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |content_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |content_hash                                                    |file_size_bytes|source_path                                                                |source_filename            |source_last_modified|ingested_at               |ingest_run_id                       |originating_system|source_format|format_detection_method|client_document_number|document_number             |drawing_revision|drawing_revision_date|header_parse_ok|project_code|ingest_date|
+------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------+---------------+---------------------------------------------------------------------------+---------------------------+--------------------+--------------------------+------------------------------------+------------------+-------------+-----------------------+----------------------+----------------------------+----------------+---------------------+---------------+------------+-----------+
|03b3f29f-364f-4aed-8e2d-16880c0f579d|[3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 22 31 2E 30 22 20 65 6E 63 6F 64 69 6E 67 3D 22 55 54 46 2D 38 22 3F 3E 0A 3C 21 2D 2D 20 53 79 6E 74 68 65 74 69 63 20 44 45 58 50 49 2F 50 72 6F 74 65 75 73 20 50 26 49 44 20 65 78 70 6F 72 74 20 28 70 72 6F 6A 65 63 74 20 41 29 2E 20 53 74 72 75 63 74 75 72 65 20 69 73 20 69 6C 6C 75 73 74 72 61 74 69 76 65 3B 0A 20 20 20 20 20 63 6F 6E 66 69 72 6D 20 72 65 61 6C 20 65 6C 65 6D 65 6E 74 2F 61 74 74 72 69 62 75 74 65 20 6E 61 6D 65 73 20 61 67 61 69 6E 73 74 20 61 63 74 75 61 6C 20 65 78 70 6F 72 74 73 20 28 73 70 65 63 20 C2 A7 39 29 2E 20 2D 2D 3E 0A 3C 50 6C 61 6E 74 4D 6F 64 65 6C 3E 0A 20 20 3C 50 6C 61 6E 74 49 6E 66 6F 72 6D 61 74 69 6F 6E 20 4F 72 69 67 69 6E 61 74 69 6E 67 53 79 73 74 65 6D 3D 22 53 6D 61 72 74 50 6C 61 6E 74 20 50 26 61 6D 70 3B 49 44 22 20 53 63 68 65 6D 61 56 65 72 73 69 6F 6E 3D 22 33 2E 36 2E 31 22 20 44 61 74 65 3D 22 32 30 32 36 2D 30 35 2D 31 30 22 2F 3E 0A 20 20 3C 44 72 61 77 69 6E 67 20 4E 61 6D 65 3D 22 33 36 32 2D 30 39 2D 50 52 2D 50 49 44 2D 30 31 30 31 30 22 0A 20 20 20 20 20 20 20 20 20 20 20 4E 75 6D 62 65 72 3D 22 32 31 35 37 37 37 43 2D 33 36 32 30 39 2D 50 49 44 2D 30 30 32 31 2D 30 31 30 31 30 22 0A 20 20 20 20 20 20 20 20 20 20 20 52 65 76 69 73 69 6F 6E 3D 22 30 31 22 0A 20 20 20 20 20 20 20 20 20 20 20 52 65 76 69 73 69 6F 6E 44 61 74 65 3D 22 32 30 32 36 2D 30 35 2D 30 38 22 3E 0A 20 20 20 20 3C 47 65 6E 65 72 69 63 41 74 74 72 69 62 75 74 65 73 20 4E 75 6D 62 65 72 3D 22 31 22 3E 0A 20 20 20 20 20 20 3C 47 65 6E 65 72 69 63 41 74 74 72 69 62 75 74 65 20 4E 61 6D 65 3D 22 44 65 73 63 72 69 70 74 69 6F 6E 22 20 56 61 6C 75 65 3D 22 41 43 49 44 20 47 41 53 20 57 41 53 48 49 4E 47 20 43 4F 4C 55 4D 4E 22 2F 3E 0A 20 20 20 20 3C 2F 47 65 6E 65 72 69 63 41 74 74 72 69 62 75 74 65 73 3E 0A 20 20 3C 2F 44 72 61 77 69 6E 67 3E 0A 20 20 3C 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 79 73 74 65 6D 20 49 44 3D 22 53 59 2D 31 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 79 73 74 65 6D 22 3E 0A 20 20 20 20 3C 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 20 49 44 3D 22 53 47 2D 31 22 3E 0A 20 20 20 20 20 20 3C 50 69 70 69 6E 67 43 6F 6D 70 6F 6E 65 6E 74 20 49 44 3D 22 50 43 2D 31 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 47 61 74 65 56 61 6C 76 65 22 2F 3E 0A 20 20 20 20 20 20 3C 50 69 70 69 6E 67 43 6F 6D 70 6F 6E 65 6E 74 20 49 44 3D 22 50 43 2D 32 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 46 6C 61 6E 67 65 22 2F 3E 0A 20 20 20 20 3C 2F 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 3E 0A 20 20 20 20 3C 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 20 49 44 3D 22 53 47 2D 32 22 3E 0A 20 20 20 20 20 20 3C 50 69 70 69 6E 67 43 6F 6D 70 6F 6E 65 6E 74 20 49 44 3D 22 50 43 2D 33 22 20 43 6F 6D 70 6F 6E 65 6E 74 43 6C 61 73 73 3D 22 43 68 65 63 6B 56 61 6C 76 65 22 2F 3E 0A 20 20 20 20 3C 2F 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 65 67 6D 65 6E 74 3E 0A 20 20 3C 2F 50 69 70 69 6E 67 4E 65 74 77 6F 72 6B 53 79 73 74 65 6D 3E 0A 3C 2F 50 6C 61 6E 74 4D 6F 64 65 6C 3E 0A]|<?xml version="1.0" encoding="UTF-8"?>\n<!-- Synthetic DEXPI/Proteus P&ID export (project A). Structure is illustrative;\n     confirm real element/attribute names against actual exports (spec §9). -->\n<PlantModel>\n  <PlantInformation OriginatingSystem="SmartPlant P&amp;ID" SchemaVersion="3.6.1" Date="2026-05-10"/>\n  <Drawing Name="362-09-PR-PID-01010"\n           Number="215777C-36209-PID-0021-01010"\n           Revision="01"\n           RevisionDate="2026-05-08">\n    <GenericAttributes Number="1">\n      <GenericAttribute Name="Description" Value="ACID GAS WASHING COLUMN"/>\n    </GenericAttributes>\n  </Drawing>\n  <PipingNetworkSystem ID="SY-1" ComponentClass="PipingNetworkSystem">\n    <PipingNetworkSegment ID="SG-1">\n      <PipingComponent ID="PC-1" ComponentClass="GateValve"/>\n      <PipingComponent ID="PC-2" ComponentClass="Flange"/>\n    </PipingNetworkSegment>\n    <PipingNetworkSegment ID="SG-2">\n      <PipingComponent ID="PC-3" ComponentClass="CheckValve"/>\n    </PipingNetworkSegment>\n  </PipingNetworkSystem>\n</PlantModel>\n|e44fe29961e23aa279cd9fffc5906bfd9a5b25ff2a30d6e3a6a74a33f56ad864|1040           |file:/home/dcamacho/dev/ProjectData/sample_data/projectA_dexpi_01010.xml   |projectA_dexpi_01010.xml   |2026-08-28 03:15:32 |2026-08-29 14:23:51.431827|38ca3858-4266-4828-a33e-d92d256fa2ae|SmartPlant P&ID   |DEXPI        |ORIGINATING_SYSTEM     |362-09-PR-PID-01010   |215777C-36209-PID-0021-01010|01              |2026-05-08           |true           |Sample      |2026-08-29 |

In [14]:
spark.stop()